# Maximum Employee Workload
MAX_EMPLOYEE_WORKLOAD: 10

# Optimization Parameters
PRESOLVE: 2
MIPFOCUS: 1
MIPGAP: 0.01
HEURISTICS: 0.8
THREADS: 2
MIPGAP_MOO: 0.05

# Objective Weights
WEIGHT_OBJ1: 0.03
WEIGHT_OBJ2: 0.9
WEIGHT_OBJ3: 0.07

# Methodology
OVERQUALIFICATION: true

# Discord Status
DISCORD: false